name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [15, 16, 17]
        oerating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.oerating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: CI=false npm run build
