name: Reusable Workflow
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Info
        run: echo "Deploying & Uploading..."
